project_id = "${VITE_SUPABASE_PROJECT_ID}"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324

[functions.generate-recurring-accounts]
verify_jwt = false

[storage]
enabled = true
port = 54326

[auth]
enabled = true
port = 54327
site_url = "https://erpnex.com.br"
additional_redirect_urls = ["https://erpnex.com.br"]

[edge_runtime]
enabled = true
port = 54328